version: "3.9"
services:
  mongodb:
    image: mongo:5.0.3
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_DATABASE: flashcards

  mongo-express:
    image: mongo-express:latest
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3023:3001"
    depends_on:
      - mongodb
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/flashcards

  app:
    build: .
    ports:
      - "3022:3000"
